"""In-memory fixtures derived from export/src/lib/mockData.ts for load_engine unit tests."""

from __future__ import annotations

from typing import Any

AS_OF = "2026-05-25"
PERIOD_START = "2026-05-19"
BLOCK_START = "2026-04-07"
USER_ID = "user-1"
CREATED_AT = "2026-04-07T06:00:00Z"

ACTIVITY_CLASSES: list[dict[str, Any]] = [
    {
        "id": "cls-foot",
        "user_id": USER_ID,
        "name": "High-Intensity Foot Load",
        "type": "performance",
        "default_recovery_window_days": 3,
        "created_at": CREATED_AT,
    },
    {
        "id": "cls-recovery",
        "user_id": USER_ID,
        "name": "Low-Impact Recovery",
        "type": "recovery",
        "default_recovery_window_days": 1,
        "created_at": CREATED_AT,
    },
    {
        "id": "cls-upper",
        "user_id": USER_ID,
        "name": "Upper Body Strength",
        "type": "performance",
        "default_recovery_window_days": 2,
        "created_at": CREATED_AT,
    },
]

ACTIVITIES: list[dict[str, Any]] = [
    {
        "id": "act-walk",
        "user_id": USER_ID,
        "activity_class_id": "cls-foot",
        "name": "Morning Walk",
        "type": "performance",
        "default_volume_unit": "km",
        "is_active": True,
        "created_at": CREATED_AT,
    },
    {
        "id": "act-bike",
        "user_id": USER_ID,
        "activity_class_id": "cls-foot",
        "name": "Stationary Bike",
        "type": "performance",
        "default_volume_unit": "minutes",
        "is_active": True,
        "created_at": CREATED_AT,
    },
    {
        "id": "act-stretch",
        "user_id": USER_ID,
        "activity_class_id": "cls-recovery",
        "name": "Light Stretching",
        "type": "recovery",
        "default_volume_unit": "minutes",
        "is_active": True,
        "created_at": CREATED_AT,
    },
    {
        "id": "act-pool",
        "user_id": USER_ID,
        "activity_class_id": "cls-recovery",
        "name": "Pool Walking",
        "type": "recovery",
        "default_volume_unit": "minutes",
        "is_active": True,
        "created_at": CREATED_AT,
    },
    {
        "id": "act-bands",
        "user_id": USER_ID,
        "activity_class_id": "cls-upper",
        "name": "Resistance Bands",
        "type": "performance",
        "default_volume_unit": "sets",
        "is_active": True,
        "created_at": CREATED_AT,
    },
]

RULES: list[dict[str, Any]] = [
    {
        "id": "rule-rest-foot",
        "training_block_id": "blk-1",
        "activity_class_id": "cls-foot",
        "rule_type": "rest_between_class",
        "threshold_value": 3,
        "window_days": 3,
        "enabled": True,
        "created_at": CREATED_AT,
    },
    {
        "id": "rule-cap-foot",
        "training_block_id": "blk-1",
        "activity_class_id": "cls-foot",
        "rule_type": "weekly_load_cap",
        "threshold_value": 120,
        "window_days": 7,
        "enabled": True,
        "created_at": CREATED_AT,
    },
    {
        "id": "rule-freq-foot",
        "training_block_id": "blk-1",
        "activity_class_id": "cls-foot",
        "rule_type": "frequency_limit",
        "threshold_value": 3,
        "window_days": 7,
        "enabled": True,
        "created_at": CREATED_AT,
    },
    {
        "id": "rule-rest-upper",
        "training_block_id": "blk-1",
        "activity_class_id": "cls-upper",
        "rule_type": "rest_between_class",
        "threshold_value": 2,
        "window_days": 2,
        "enabled": True,
        "created_at": CREATED_AT,
    },
]

WEEKLY_TARGETS: list[dict[str, Any]] = [
    {
        "id": "wt-foot",
        "training_block_id": "blk-1",
        "activity_class_id": "cls-foot",
        "target_value": 8,
        "target_unit": "km",
        "created_at": CREATED_AT,
    },
    {
        "id": "wt-recovery",
        "training_block_id": "blk-1",
        "activity_class_id": "cls-recovery",
        "target_value": 4,
        "target_unit": "sessions",
        "created_at": CREATED_AT,
    },
]

LOGS: list[dict[str, Any]] = [
    {
        "id": "log-01",
        "user_id": USER_ID,
        "activity_id": "act-walk",
        "logged_date": "2026-04-08",
        "duration_minutes": 20,
        "volume_value": 1.5,
        "volume_unit": "km",
        "rpe": 3,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-02",
        "user_id": USER_ID,
        "activity_id": "act-bands",
        "logged_date": "2026-04-10",
        "duration_minutes": 30,
        "volume_value": 3,
        "volume_unit": "sets",
        "rpe": 3,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-03",
        "user_id": USER_ID,
        "activity_id": "act-stretch",
        "logged_date": "2026-04-12",
        "duration_minutes": 15,
        "volume_value": 15,
        "volume_unit": "minutes",
        "rpe": 1,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-04",
        "user_id": USER_ID,
        "activity_id": "act-walk",
        "logged_date": "2026-04-14",
        "duration_minutes": 25,
        "volume_value": 2.0,
        "volume_unit": "km",
        "rpe": 4,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-05",
        "user_id": USER_ID,
        "activity_id": "act-stretch",
        "logged_date": "2026-04-16",
        "duration_minutes": 20,
        "volume_value": 20,
        "volume_unit": "minutes",
        "rpe": 1,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-06",
        "user_id": USER_ID,
        "activity_id": "act-walk",
        "logged_date": "2026-04-17",
        "duration_minutes": 25,
        "volume_value": 2.5,
        "volume_unit": "km",
        "rpe": 5,
        "post_activity_feel": "mild_discomfort",
        "rule_violations_at_log": [
            {
                "rule_id": "rule-rest-foot",
                "rule_type": "rest_between_class",
                "message": "Only 3 days since last foot-load session — rest window not complete",
                "severity": "caution",
            }
        ],
        "created_at": CREATED_AT,
    },
    {
        "id": "log-07",
        "user_id": USER_ID,
        "activity_id": "act-pool",
        "logged_date": "2026-04-19",
        "duration_minutes": 20,
        "volume_value": 20,
        "volume_unit": "minutes",
        "rpe": 2,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-08",
        "user_id": USER_ID,
        "activity_id": "act-walk",
        "logged_date": "2026-04-21",
        "duration_minutes": 30,
        "volume_value": 3.0,
        "volume_unit": "km",
        "rpe": 5,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-09",
        "user_id": USER_ID,
        "activity_id": "act-pool",
        "logged_date": "2026-04-22",
        "duration_minutes": 30,
        "volume_value": 30,
        "volume_unit": "minutes",
        "rpe": 2,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-10",
        "user_id": USER_ID,
        "activity_id": "act-bike",
        "logged_date": "2026-04-24",
        "duration_minutes": 20,
        "volume_value": 20,
        "volume_unit": "minutes",
        "rpe": 5,
        "post_activity_feel": "bad",
        "rule_violations_at_log": [
            {
                "rule_id": "rule-rest-foot",
                "rule_type": "rest_between_class",
                "message": "Breaks 3-day rest rule for foot load — only 3 days since morning walk",
                "severity": "caution",
            }
        ],
        "created_at": CREATED_AT,
    },
    {
        "id": "log-11",
        "user_id": USER_ID,
        "activity_id": "act-stretch",
        "logged_date": "2026-04-28",
        "duration_minutes": 15,
        "volume_value": 15,
        "volume_unit": "minutes",
        "rpe": 1,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-12",
        "user_id": USER_ID,
        "activity_id": "act-pool",
        "logged_date": "2026-04-30",
        "duration_minutes": 20,
        "volume_value": 20,
        "volume_unit": "minutes",
        "rpe": 2,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-13",
        "user_id": USER_ID,
        "activity_id": "act-stretch",
        "logged_date": "2026-05-02",
        "duration_minutes": 15,
        "volume_value": 15,
        "volume_unit": "minutes",
        "rpe": 1,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-14",
        "user_id": USER_ID,
        "activity_id": "act-walk",
        "logged_date": "2026-05-05",
        "duration_minutes": 20,
        "volume_value": 1.5,
        "volume_unit": "km",
        "rpe": 3,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-15",
        "user_id": USER_ID,
        "activity_id": "act-pool",
        "logged_date": "2026-05-07",
        "duration_minutes": 25,
        "volume_value": 25,
        "volume_unit": "minutes",
        "rpe": 2,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-16",
        "user_id": USER_ID,
        "activity_id": "act-walk",
        "logged_date": "2026-05-09",
        "duration_minutes": 25,
        "volume_value": 2.0,
        "volume_unit": "km",
        "rpe": 4,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-17",
        "user_id": USER_ID,
        "activity_id": "act-bands",
        "logged_date": "2026-05-11",
        "duration_minutes": 30,
        "volume_value": 3,
        "volume_unit": "sets",
        "rpe": 3,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-18",
        "user_id": USER_ID,
        "activity_id": "act-pool",
        "logged_date": "2026-05-12",
        "duration_minutes": 30,
        "volume_value": 30,
        "volume_unit": "minutes",
        "rpe": 2,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-19",
        "user_id": USER_ID,
        "activity_id": "act-walk",
        "logged_date": "2026-05-13",
        "duration_minutes": 30,
        "volume_value": 2.5,
        "volume_unit": "km",
        "rpe": 5,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-20",
        "user_id": USER_ID,
        "activity_id": "act-pool",
        "logged_date": "2026-05-14",
        "duration_minutes": 30,
        "volume_value": 30,
        "volume_unit": "minutes",
        "rpe": 2,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-21",
        "user_id": USER_ID,
        "activity_id": "act-bike",
        "logged_date": "2026-05-15",
        "duration_minutes": 20,
        "volume_value": 20,
        "volume_unit": "minutes",
        "rpe": 5,
        "post_activity_feel": "mild_discomfort",
        "rule_violations_at_log": [
            {
                "rule_id": "rule-rest-foot",
                "rule_type": "rest_between_class",
                "message": "Breaks 3-day rest rule for foot load — 2 days since last walk",
                "severity": "caution",
            }
        ],
        "created_at": CREATED_AT,
    },
    {
        "id": "log-22",
        "user_id": USER_ID,
        "activity_id": "act-walk",
        "logged_date": "2026-05-16",
        "duration_minutes": 30,
        "volume_value": 3.0,
        "volume_unit": "km",
        "rpe": 7,
        "post_activity_feel": "bad",
        "rule_violations_at_log": [
            {
                "rule_id": "rule-rest-foot",
                "rule_type": "rest_between_class",
                "message": "Breaks 3-day rest rule for foot load — 1 day since last session",
                "severity": "danger",
            }
        ],
        "created_at": CREATED_AT,
    },
    {
        "id": "log-23",
        "user_id": USER_ID,
        "activity_id": "act-stretch",
        "logged_date": "2026-05-19",
        "duration_minutes": 15,
        "volume_value": 15,
        "volume_unit": "minutes",
        "rpe": 1,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-24",
        "user_id": USER_ID,
        "activity_id": "act-pool",
        "logged_date": "2026-05-21",
        "duration_minutes": 20,
        "volume_value": 20,
        "volume_unit": "minutes",
        "rpe": 2,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-25",
        "user_id": USER_ID,
        "activity_id": "act-walk",
        "logged_date": "2026-05-22",
        "duration_minutes": 20,
        "volume_value": 1.5,
        "volume_unit": "km",
        "rpe": 3,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
    {
        "id": "log-26",
        "user_id": USER_ID,
        "activity_id": "act-bands",
        "logged_date": "2026-05-24",
        "duration_minutes": 30,
        "volume_value": 3,
        "volume_unit": "sets",
        "rpe": 2,
        "post_activity_feel": "fine",
        "created_at": CREATED_AT,
    },
]

CHECK_INS: list[dict[str, Any]] = [
    {
        "id": "ci-1",
        "user_id": USER_ID,
        "check_in_date": "2026-04-24",
        "pain_level": 7,
        "readiness_level": 2,
        "stiffness_level": 8,
        "has_flare_up": True,
        "created_at": CREATED_AT,
    },
    {
        "id": "ci-2",
        "user_id": USER_ID,
        "check_in_date": "2026-04-28",
        "pain_level": 4,
        "readiness_level": 4,
        "stiffness_level": 5,
        "has_flare_up": False,
        "created_at": CREATED_AT,
    },
    {
        "id": "ci-3",
        "user_id": USER_ID,
        "check_in_date": "2026-05-05",
        "pain_level": 2,
        "readiness_level": 7,
        "stiffness_level": 3,
        "has_flare_up": False,
        "created_at": CREATED_AT,
    },
    {
        "id": "ci-4",
        "user_id": USER_ID,
        "check_in_date": "2026-05-16",
        "pain_level": 8,
        "readiness_level": 1,
        "stiffness_level": 9,
        "has_flare_up": True,
        "created_at": CREATED_AT,
    },
    {
        "id": "ci-5",
        "user_id": USER_ID,
        "check_in_date": "2026-05-22",
        "pain_level": 2,
        "readiness_level": 7,
        "stiffness_level": 3,
        "has_flare_up": False,
        "created_at": CREATED_AT,
    },
    {
        "id": "ci-6",
        "user_id": USER_ID,
        "check_in_date": "2026-05-24",
        "pain_level": 1,
        "readiness_level": 8,
        "stiffness_level": 2,
        "has_flare_up": False,
        "created_at": CREATED_AT,
    },
]

INCIDENTS: list[dict[str, Any]] = [
    {
        "id": "inc-1",
        "user_id": USER_ID,
        "incident_date": "2026-04-24",
        "body_part": "Left heel",
        "severity": 6,
        "activity_class_id": "cls-foot",
        "daily_check_in_id": "ci-1",
        "created_at": CREATED_AT,
    },
    {
        "id": "inc-2",
        "user_id": USER_ID,
        "incident_date": "2026-05-16",
        "body_part": "Left heel",
        "severity": 8,
        "activity_class_id": "cls-foot",
        "daily_check_in_id": "ci-4",
        "created_at": CREATED_AT,
    },
]
